/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.lab.util.app;

import com.epam.lab.util.list.Utils;

public class App {

    public static void main(String[] args) {
        final boolean result = Utils.isAllPositiveNumbers("12", "79");
        System.out.println(result);
    }
}
